{% set name = "ipysheet" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7af431f31f64141099168e2a78310a6039022896d728e07a4e1b3e58e4ab6df6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - ipywidgets>=7.0.0,<8.0

test:
  imports:
    - ipysheet

about:
  home: http://github.com/QuantStack/ipysheet
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Spreadsheet widget for Jupyter'
  description: 'Spreadsheet widget for Jupyter'
  dev_url: https://github.com/QuantStack/ipysheet
  dev_url: https://github.com/QuantStack/ipysheet

extra:
  recipe-maintainers:
    - SylvainCorlay
    - MaartenBreddels
