travis:
  secure:
    BINSTAR_TOKEN: mYS3dznC5/5h1J9VguNcS/jOaXuWKJDnYpjJm7OWdEWuY2uuE1/u9LIFrd5HKh/6TgVSvBlokWASngdJks98K0AGCgo2AOkrSqMtB2vDZSkfWww9PqSNo4LzhCz9TsLAULSF9o8U6BniL4cCt9N/3dQZ9J6WnQ4OKsHKrBz4P4qwzZFVBO0ukRUxKMJxsNw+WTnvFswdieP4nknB9IzX2LJwcd3QWn6HoA0mqzTElo0R8Q+0wl5TVOlu3EMNqnwlmC5fZf2ghIX/ZK0t2hTf09z2aT/dapb1m3qYcHxGYkk65Y7PbrbMSQzJ/TO98uEFecRBniRUiOh5ImtEJ9PTsNIu7BTqsEUKekHRBPx6Z82NCIJqaWEtuDuY5FMrZJhp8lLR+tNahEvhtBmSUGvxpuSl2Lzez8kuaLYOA0Qch6590SgnDkYc9QyWftwgSBubovGf5fSuMT/R+fUvyTRh0TmD+xE08EbRNby+NEqjjWkfxPuoF/fCi1WQqG1YI3lVGPXag8nOJK6zO99PPnDpSby4A0Ohz7OYB/HzAX0YuJUQcVjV+tk3AlComqTsmPrxOGiRAz8fSkov/yEmKz0AI4GbFj6i1ok/3YHJixL9gGGH6QN7OjZxwHYuLAfS4iNMtSoWx0+01CMHGyXG0lt2D2++39NQtn1wow4rcKSdkjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
