travis:
  secure:
    BINSTAR_TOKEN: AK0PENdI+m1A1+oKu0fb/3GpD5OJ3GugBaZZNk7c9Akx4WJFW9jnFALydmijSUIZ/8P+gSsHUVM1KDtG3+hJYx1FHMAvUIS44h14HEL12zOSdBAhvq4Lw0eUH4yK/GyH1AB8vnnK9FB6iDdJgqiFRy7sdSN6WpJ5AlgyjXVXb1HlSPXjRsDCdoXoE0yh0sNvJRozbIpnbsJCmh27iYX3ACx8pQQEOnmS9k3igh3eHd8fArCK2EzId1pat+ge9XOtfcDRhUUluc6zEhvaW64YjJfyq8Qy45s36N6vUms7ntsjDcHq7a+DPmHlC2FnAF6oS4zYXFLyMXUhfVM6WUi+fqOA9AEx5+RQC11SuuZa+9rwN1CfWJZNZ3dnnmm3LTJbBEuAnHDTkuafjPXPdK1y533iSKAjQdwV1n6C22dPPWVpw4/QOuSBXkvZpsdRrkFatkT4ZAXyub7JMIlM1zJXEu4k+ha5mSE+TZA1Tu3J7CErlwE/awOMyrKM43RHdMkcuHQLcZXZQgjpVBce6k2kmWB9E0c0DgJf38fFq/XdlQkezUSkDeEWa9ohAk2M5ZyBlcLltXENaiK2k1dk3b6PmKvH3vr+VDyEicBr/GZDh4ValnKu5B85fT6iptcROiZ0rmsFPaOOzhI14nTuIbVayJWuqPaOs+zatnh84TzVkgg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
